# Linear Algebra 1

In [1]:
# Import necessary libraries
import numpy as np
import scipy as sc
# Define the coefficient matrix A
A = np.array([[1, 3, 5], [2, 5, 1], [2, 3, 8]])
print(A)


[[1 3 5]
 [2 5 1]
 [2 3 8]]


In [2]:
# Define the right-hand side vector b
b = np.array([[10], [8], [3]])
print(b)

[[10]
 [ 8]
 [ 3]]


In [3]:
# Calculate the inverse of A and multiply by b to find the solution vector
C = sc.linalg.inv(A).dot(b) # linear algebra which calc inverse of matrix A times with matrix b
print(C)

[[-9.28]
 [ 5.16]
 [ 0.76]]


In [4]:
# Alternatively, use the solve function to find the solution vector directly
D = sc.linalg.solve(A, b)
print(D)

[[-9.28]
 [ 5.16]
 [ 0.76]]


# Linear Algebra 2

In [5]:
import numpy as np
from scipy.linalg import solve
# Coefficients matrix
A = np.array([[3, 2], [1, 2]])
print(A)

[[3 2]
 [1 2]]


In [6]:
# Constants vector
b = np.array([1, 0])
print(b)

[1 0]


In [7]:
# Using the solve function to find the solution to the system of equations
solution = solve(A, b)
print(solution)


[ 0.5  -0.25]


# Runge-Kutta method